#!/usr/bin/env python3

import argparse
import os

import rosbag
from colorama import Fore, Style
from pytictoc import TicToc
from tqdm import tqdm

from rosbag_tools.config_camera_intrinsics import config_camera_intrinsics

"""
Usage:

./config_camera_intrinsics -bfi original.bag -ct camera/camera_info -d 0.6 -2.2 -0.0 0.0 0.0 -k 2125.6 0.0 1018.8 0.0 2056.6 549.2 0.0 0.0 1.0 -r 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 -p 2210.4 0.0 1025.5 0.0 0.0 2148.7 537.7 0.0 0.0 0.0 1.0 0.0
"""

if __name__ == "__main__":
    # Parse command line arguments
    ap = argparse.ArgumentParser()
    ap.add_argument("-bfi", "--bagfile_in", help='Full path to the bagfile', type=str, required=True)
    ap.add_argument("-bfo", "--bagfile_out", help='Full path to output the bagfile. If not given will be named out.bag and placed on the same folder as the input bag.', type=str, required=False)
    ap.add_argument("-ct", "--camera_topic", help='Camera topic. Example: ... -ct camera/camera_info', type=str, required=True)
    ap.add_argument("-d", "--distortion", help='Camera distortion. Example: ... -d 0.6 -2.2 -0.0 0.0 0.0', type=float, required=False, nargs='+')
    ap.add_argument("-k", "--k_matrix", help='Camera k matrix. Example: ... -k 2125.6 0.0 1018.8 0.0 2056.6 549.2 0.0 0.0 1.0', type=float, required=False, nargs='+')
    ap.add_argument("-r", "--r_matrix", help='Camera r matrix. Example: ... -r 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0', type=float, required=False, nargs='+')
    ap.add_argument("-p", "--p_matrix", help='Camera p matrix. Example: ... -p 2210.4 0.0 1025.5 0.0 0.0 2148.7 537.7 0.0 0.0 0.0 1.0 0.0', type=float, required=False, nargs='+')
    
    args = vars(ap.parse_args())
    
    if args['bagfile_out'] is None:
        path = os.path.dirname(args['bagfile_in'])
        args['bagfile_out'] = path + '/out.bag'
    
    config_camera_intrinsics(args['bagfile_in'], args['bagfile_out'], args['camera_topic'], args['distortion'], args['k_matrix'], args['r_matrix'], args['p_matrix'])
