#!/usr/bin/env python3

# stdlib
import argparse
from copy import deepcopy

# 3rd-party
import rosbag
from tqdm import tqdm
from colorama import Fore, Style
from tf2_msgs.msg import TFMessage
from geometry_msgs.msg import TransformStamped, Transform
from pytictoc import TicToc

# local packages

if __name__ == "__main__":
    # Parse command line arguments
    ap = argparse.ArgumentParser()
    # ap.add_argument("-bfi", "--bagfile_in", help='Full path to the bagfile', type=str, required=True)
    # ap.add_argument("-bfo", "--bagfile_out", help='Full path to the bagfile', type=str, required=True)
    # ap.add_argument("-p", "--parent", help='Transform parent', type=str, required=True)
    # ap.add_argument("-c", "--child", help='Transform child', type=str, required=True)
    ap.add_argument("-bfi", "--bagfile_in", help='Full path to the bagfile', type=str, default='/home/mike/bagfiles/zaubot/zau_full_calibration_train_bag.bag')
    ap.add_argument("-bfo", "--bagfile_out", help='Full path to the bagfile', type=str, default='/home/mike/bagfiles/zaubot/test.bag')
    ap.add_argument("-p", "--parent", help='Transform parent', type=str, default='zau/base_link')
    ap.add_argument("-c", "--child", help='Transform child', type=str, default='base_link')

    args = vars(ap.parse_args())

    # --------------------------------------------------------------------------
    # Initial setup
    # --------------------------------------------------------------------------
    import rosbag
    from std_msgs.msg import Int32, String

    bag = rosbag.Bag('test.bag', 'w')
    bag

    try:
        str = String()
        str.data = 'foo'

        i = Int32()
        i.data = 42

        connection_header = {
            'topic': 'chatter',
            'type': String,
            'md5sum': md5sum,
            'message_definition': pytype._full_text
        }

        bag.write('chatter', str, connection_header=)
        bag.write('numbers', i)
    finally:
        bag.close()